### ISSUE TITLE
RPC client: Exception on shutdown

### ISSUE THREAD

**Issue by barakp** [sandstorm-io/capnproto#382]
Happened during RPC client shutdown. backtrace:

```
#0  0x00007fc1a59a80db in capnp::_::(anonymous namespace)::RpcConnectionState::disconnect(kj::Exception&&)::{lambda()#1}::operator()() const ()
   from /lib64/libcapnp-rpc-0.6-dev.so
#1  0x00007fc1a5726f16 in kj::_::runCatchingExceptions(kj::_::Runnable&) () from /lib64/libkj-0.6-dev.so
#2  0x00007fc1a59a7c16 in capnp::_::(anonymous namespace)::RpcConnectionState::disconnect(kj::Exception&&) () from /lib64/libcapnp-rpc-0.6-dev.so
#3  0x00007fc1a59b3bb9 in capnp::_::(anonymous namespace)::RpcConnectionState::messageLoop()::{lambda(kj::Maybe<kj::Own<capnp::IncomingRpcMessage> >&&)#1}::operator()(kj::Maybe<kj::Own<capnp::IncomingRpcMessage> >&&) const () from /lib64/libcapnp-rpc-0.6-dev.so
#4  0x00007fc1a59b515b in kj::_::TransformPromiseNode<bool, kj::Maybe<kj::Own<capnp::IncomingRpcMessage> >, capnp::_::(anonymous namespace)::RpcConnectionState::messageLoop()::{lambda(kj::Maybe<kj::Own<capnp::IncomingRpcMessage> >&&)#1}, kj::_::PropagateException>::getImpl(kj::_::ExceptionOrValue&) () from /lib64/libcapnp-rpc-0.6-dev.so
#5  0x00007fc1a54eba22 in kj::_::RunnableImpl<kj::_::TransformPromiseNodeBase::get(kj::_::ExceptionOrValue&)::{lambda()#1}>::run() () from /lib64/libkj-async-0.6-dev.so
#6  0x00007fc1a5726f16 in kj::_::runCatchingExceptions(kj::_::Runnable&) () from /lib64/libkj-0.6-dev.so
#7  0x00007fc1a54eb46d in kj::_::TransformPromiseNodeBase::get(kj::_::ExceptionOrValue&) () from /lib64/libkj-async-0.6-dev.so
#8  0x00007fc1a54eba5c in kj::_::TransformPromiseNodeBase::getDepResult(kj::_::ExceptionOrValue&) () from /lib64/libkj-async-0.6-dev.so
#9  0x00007fc1a59b8157 in kj::_::TransformPromiseNode<kj::_::Void, bool, capnp::_::(anonymous namespace)::RpcConnectionState::messageLoop()::{lambda(bool)#2}, kj::_::PropagateException>::getImpl(kj::_::ExceptionOrValue&) () from /lib64/libcapnp-rpc-0.6-dev.so
#10 0x00007fc1a54eba22 in kj::_::RunnableImpl<kj::_::TransformPromiseNodeBase::get(kj::_::ExceptionOrValue&)::{lambda()#1}>::run() () from /lib64/libkj-async-0.6-dev.so
#11 0x00007fc1a5726f16 in kj::_::runCatchingExceptions(kj::_::Runnable&) () from /lib64/libkj-0.6-dev.so
#12 0x00007fc1a54eb46d in kj::_::TransformPromiseNodeBase::get(kj::_::ExceptionOrValue&) () from /lib64/libkj-async-0.6-dev.so
#13 0x00007fc1a54f18fb in kj::_::TaskSetImpl::Task::fire() () from /lib64/libkj-async-0.6-dev.so
#14 0x00007fc1a54ec707 in kj::EventLoop::turn() () from /lib64/libkj-async-0.6-dev.so
#15 0x00007fc1a54ef7c8 in kj::_::waitImpl(kj::Own<kj::_::PromiseNode>&&, kj::_::ExceptionOrValue&, kj::WaitScope&) () from /lib64/libkj-async-0.6-dev.so
#16 0x00000000007d4340 in kj::Promise<void>::wait (this=this@entry=0x7ffeb8ba7c50, waitScope=...) at /usr/include/kj/async-inl.h:806
```

**Comment by kentonv** [comment]
If this was an exception, what was the description message? Or was it actually a segfault? Is it reproducible?

**Comment by barakp** [comment]
Oh it was actually a segfault. I think it's reproducible. Let me know what you need.

**Comment by kentonv** [comment]
Can you provide a minimal self-contained test program that triggers the segfault?

**Comment by barakp** [comment]
Sorry - this seems to be a bug in our code. I'll let you know if this reproduces independently. Closing.
